language: node_js
node_js:
    - "6.11.2"
sudo: required

addons:
  sonarcloud:
    organization: "jpl154-github"
    token:
      secure: $SONAR_TOKEN
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.sonar/cache'
    - node_modules

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on:
    branch: release
  bucket: $AWS_BUCKET_NAME
  region: $AWS_BUCKET_REGION
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: yourBucketNameHERE
  key: latest.zip
  bundle_type: zip
  application: NameOfTheCodeDeployApplicationNameHERE
  deployment_group: CodeDeployDeploymentGroupNameHERE
  region: serverRegionHERE
  on:
    branch: release


script:
  - sonar-scanner
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
